### ISSUE TITLE
error while compiling pciesvc

### ISSUE THREAD

**Issue by ashwin-h** [pensando/dsc-drivers#23]
@jbradleysmith when i tried to compile on debian 5.10.140 version of the kernel with below compiler
aarch64-linux-gnu-gcc (Linaro GCC 6.4-2017.08) 6.4.1 20170707

I see this error

```
aarch64-linux-gnu-gcc: error: unrecognized command line option --fno-store-merging; did you mean --fno-store-check?
```

for now i removed -fno-store-merging in my local workspace.

**Comment by jbradleysmith** [comment]
> for now i removed -fno-store-merging in my local workspace.

Yes, that is the proper workaround if the toolchain doesn't yet support this option.
